/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Model.Atendimento;
import Model.User;
import controller.AtendimentoController;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author gabri
 */
public class FrAtendimentos extends javax.swing.JFrame {
    
    private JFrame parent;
    private AtendimentoController gerenciadorAtendimento;
    private TMcadAtendimento tableModel;
    private User usuarioLogado;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrAtendimentos.class.getName());
    /**
     * Creates new form FrAtendimentosF
     */
    public FrAtendimentos(JFrame parent) {
        this.parent = parent;
        initComponents();
        this.gerenciadorAtendimento = new AtendimentoController();
        this.usuarioLogado = null; // Modo genérico (admin)
        atualizarTabela();
    }
    
    public FrAtendimentos(User usuario) {
        initComponents();
        this.gerenciadorAtendimento = new AtendimentoController();
        this.usuarioLogado = usuario; // Recebe quem logou
        
        configurarPermissoes(); // Ajusta a tela
        atualizarTabela();      // Carrega os dados corretos
    }
    
    
    private void configurarPermissoes() {
        if (this.usuarioLogado != null && this.usuarioLogado.getNivelAcesso() == 3) {
            // Se for Cliente (Nível 3):
            btnNovo.setVisible(false); // Esconde o botão Novo
            lblTitle.setText("Meus Atendimentos"); // (Opcional) Muda o título
        } else {
            // Se for Admin/Técnico:
            btnNovo.setVisible(true);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNovo = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridCadAtendimento = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNovo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        gridCadAtendimento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(gridCadAtendimento);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setText("Painel - Atendimentos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // Abre o formulário de cadastro de atendimento.
<<<<<<< HEAD
        FrcadAtendimento cadAtendimentos = new FrcadAtendimento(this, true);
        cadAtendimentos.setLocationRelativeTo(this);
        cadAtendimentos.setVisible(true);
=======
        // Visível somente para nível técnico e gerente.
        FrcadAtendimento telaCadastro = new FrcadAtendimento(this, true);
        telaCadastro.setLocationRelativeTo(this);
        telaCadastro.setVisible(true);
        atualizarTabela();
>>>>>>> 77d91c18d0ae19ab4c00b601b51c1f3fb5238355
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        if (this.parent != null) {
            this.parent.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public void atualizarTabela() {
        List<Atendimento> lista;
        
        // Decide qual lista carregar
        if (this.usuarioLogado != null && this.usuarioLogado.getNivelAcesso() == 3) {
            // Busca filtrada
            lista = this.gerenciadorAtendimento.listarPorCliente(this.usuarioLogado.getId());
        } else {
            // Busca tudo
            lista = this.gerenciadorAtendimento.listarTodos();
        }
        
        // O resto continua igual...
        view.TMcadAtendimento tmcadAtendimento = new view.TMcadAtendimento(lista);
        gridCadAtendimento.setModel(tmcadAtendimento);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTable gridCadAtendimento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
