/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import Model.Cliente;
import Model.Tecnico;
import Model.User;
import controller.UsuarioDAO;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class FrcadAtendimento extends javax.swing.JDialog {
    
    private DefaultListModel<String> servicesModel;
    private DefaultListModel<String> valuesModel;
    private double totalAtendimento = 0.0;
    
    /**
     * Creates new form FrcadAtendimento
     */
    public FrcadAtendimento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        servicesModel = new DefaultListModel<>();
        valuesModel = new DefaultListModel<>();
        
        initComponents();
        
        listServices.setModel(servicesModel);
        listValues.setModel(valuesModel);
        
        edtTotal.setText(String.format("%.2f", totalAtendimento));
        edtTotal.setEditable(false); // Geralmente, o total é apenas exibido
        
        popularCombos();
    }
    
    private void atualizarTotal() {
        edtTotal.setText(String.format("%.2f", totalAtendimento));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        lblTitle = new javax.swing.JLabel();
        SelBoxTecnico = new javax.swing.JComboBox<>();
        lblTecnico = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        SelBoxCliente = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listValues = new javax.swing.JList<>();
        lblServicos = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        SelBoxStatus = new javax.swing.JComboBox<>();
        btnFinish = new javax.swing.JToggleButton();
        btnCancel = new javax.swing.JToggleButton();
        lblTotal = new javax.swing.JLabel();
        edtTotal = new javax.swing.JTextField();
        lblDescription = new javax.swing.JLabel();
        edtDescription = new javax.swing.JTextField();
        lblValue = new javax.swing.JLabel();
        edtValue = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listServices = new javax.swing.JList<>();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setText("Cadastro de Atendimento");

        SelBoxTecnico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SelBoxTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelBoxTecnicoActionPerformed(evt);
            }
        });

        lblTecnico.setText("Técnico:");

        lblCliente.setText("Cliente:");

        SelBoxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SelBoxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelBoxClienteActionPerformed(evt);
            }
        });

        listValues.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listValues);

        lblServicos.setText("Serviços:");

        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setText("Adicionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblStatus.setText("Status:");

        SelBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnFinish.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFinish.setText("Finalizar");
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotal.setText("Total:");

        lblDescription.setText("Descrição:");

        lblValue.setText("Valor:");

        listServices.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listServices);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTecnico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SelBoxTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SelBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SelBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblServicos)
                                .addGap(45, 45, 45)
                                .addComponent(lblDescription))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(lblValue)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edtDescription)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdd))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SelBoxTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTecnico)
                            .addComponent(lblCliente)
                            .addComponent(SelBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblServicos)
                            .addComponent(lblDescription)
                            .addComponent(edtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblStatus)
                        .addComponent(SelBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValue)
                    .addComponent(edtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelBoxTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelBoxTecnicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelBoxTecnicoActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String descricao = edtDescription.getText().trim();
        String valorStr = edtValue.getText().trim().replace(",", "."); // Aceita vírgula como separador decimal
        double valor;

        // 1. Validação
        if (descricao.isEmpty() || valorStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "A Descrição e o Valor não podem ser vazios.", "Erro de Entrada", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // 2. Transforma o valor em Double
            valor = Double.parseDouble(valorStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "O valor inserido não é um número válido.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Adiciona os valores às JLists
        // Descrição adicionada em listServices
        servicesModel.addElement(descricao); 
        
        // Valor adicionado em listValues (formatado para 2 casas decimais)
        valuesModel.addElement(String.format("%.2f", valor)); 

        // 4. Soma o valor ao total
        totalAtendimento += valor;
        
        // 5. Atualiza o campo edtTotal
        atualizarTotal();

        // 6. Limpa os campos de entrada
        edtDescription.setText("");
        edtValue.setText("");
        
        // Opcional: Define o foco para o próximo item de entrada
        edtDescription.requestFocus();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        try {
            // 1. Cria o objeto Atendimento
            Model.Atendimento atendimento = new Model.Atendimento();
            
            // 2. Pega os objetos selecionados nas ComboBoxes (Fazendo Cast)
            atendimento.setCliente((Cliente) SelBoxCliente.getSelectedItem());
            atendimento.setTecnico((Tecnico) SelBoxTecnico.getSelectedItem());
            atendimento.setStatus((String) SelBoxStatus.getSelectedItem());
            
            // 3. Pega os dados dos campos de texto
            // Nota: jTextField2 é o campo de valor/preço na sua tela
            atendimento.setPreco(edtTotal.getText()); 
            
            // Define a data atual automaticamente
            atendimento.setData_atendimento(java.time.LocalDate.now().toString());
            
            // Descrição: Como não tem um campo de texto específico, 
            // vamos pegar o item selecionado na lista de serviços ou um texto padrão
            String servicoSelecionado = listServices.getSelectedValue();
            if (servicoSelecionado != null) {
                atendimento.setDescricao(servicoSelecionado);
            } else {
                atendimento.setDescricao("Manutenção Geral (Não especificado)");
            }

            // 4. Chama o Controller para salvar
            controller.AtendimentoController controller = new controller.AtendimentoController();
            controller.salvarAtendimento(atendimento);
            
            // 5. Fecha a janela após salvar
            this.dispose();
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Erro ao salvar: " + e.getMessage(), 
                "Erro", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnFinishActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void SelBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelBoxClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelBoxClienteActionPerformed

    

    private void popularCombos() {
        UsuarioDAO dao = new UsuarioDAO();

        // 1. Configura a caixa de Clientes
        SelBoxCliente.removeAllItems();
        List<Cliente> clientes = dao.listarClientes(); // Use o método específico que criamos
        for (Cliente c : clientes) {
            // Agora adicionamos o OBJETO inteiro (graças ao passo 1, aparecerá só o nome)
            SelBoxCliente.addItem(c);
        }

        // 2. Configura a caixa de Técnicos
        SelBoxTecnico.removeAllItems();
        List<Tecnico> tecnicos = dao.listarTecnicos();
        for (Tecnico t : tecnicos) {
            SelBoxTecnico.addItem(t);
        }

        // 3. Configura a caixa de Status (Hardcoded por enquanto)
        SelBoxStatus.removeAllItems();
        SelBoxStatus.addItem("Aberto");
        SelBoxStatus.addItem("Em Andamento");
        SelBoxStatus.addItem("Aguardando Peças");
        SelBoxStatus.addItem("Concluído");
        SelBoxStatus.addItem("Cancelado");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> SelBoxCliente;
    private javax.swing.JComboBox<String> SelBoxStatus;
    private javax.swing.JComboBox<Object> SelBoxTecnico;
    private javax.swing.JButton btnAdd;
    private javax.swing.JToggleButton btnCancel;
    private javax.swing.JToggleButton btnFinish;
    private javax.swing.JTextField edtDescription;
    private javax.swing.JTextField edtTotal;
    private javax.swing.JTextField edtValue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblServicos;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTecnico;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblValue;
    private javax.swing.JList<String> listServices;
    private javax.swing.JList<String> listValues;
    // End of variables declaration//GEN-END:variables
}
