/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Model.Cliente;
import Model.Feedback;
import java.util.List;
import Model.Cliente;
import Model.Feedback;
import Model.User;                  
import controller.FeedbackController; 
import java.awt.event.WindowAdapter;  
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author superbi
 */
public class frFeedbackF extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frFeedbackF.class.getName());
    private User usuarioLogado;
    private FeedbackController controller;
    private FeedbackTableModel tableModel;

    /**
     * Creates new form frFeedbackF
     */
    
    public frFeedbackF(User usuario) { // <--- Agora recebe o usuário
        initComponents();
        
        this.usuarioLogado = usuario;
        this.controller = new FeedbackController();
        
        // Verifica se o usuário chegou nulo (segurança)
        if (this.usuarioLogado == null) {
            JOptionPane.showMessageDialog(this, "Erro: Usuário não identificado.");
            this.dispose();
            return;
        }

        configurarPermissoes();
        atualizarTabela();
        
        setLocationRelativeTo(null); // Centraliza a janela na tela
    }
    public frFeedbackF() {
        initComponents();
    }
    
    private void configurarPermissoes() {
        // Se for Cliente (nível 3 ou instância de Cliente), vê o botão
        if (this.usuarioLogado instanceof Cliente) {
            btnDarFeedback.setVisible(true);
        } else {
            // Gerente ou Técnico não dão feedback, só leem
            btnDarFeedback.setVisible(false);
        }
        // O botão voltar aparece para todos
    }

    // --- MÉTODO 2: Atualizar Tabela ---
    private void atualizarTabela() {
        List<Feedback> dados;

        // 1. Busca os dados corretos dependendo de quem está logado
        if (this.usuarioLogado instanceof Cliente) {
            // Se for cliente, busca só os dele
            dados = controller.listarPorCliente(this.usuarioLogado.getId());
        } else {
            // Se for admin/técnico, busca todos
            dados = controller.listarTodos();
        }

        // 2. Configura o modelo na tabela (JTable)
        if (tableModel == null) {
            // Cria o modelo pela primeira vez
            tableModel = new FeedbackTableModel(dados);
            gridComentarios.setModel(tableModel);
        } else {
            // Se o modelo já existe, apenas atualiza a lista interna dele
            tableModel.setLista(dados);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDarFeedback = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridComentarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDarFeedback.setText("Dar Feedback");
        btnDarFeedback.addActionListener(this::btnDarFeedbackActionPerformed);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);

        gridComentarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(gridComentarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDarFeedback)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnVoltar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDarFeedback)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVoltar)))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDarFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarFeedbackActionPerformed
        // Cria a tela de cadastro (FrCadFeedback)
        // Passamos o usuarioLogado (Cliente) para ele saber quem está a criar
        FrCadFeedback telaCadastro = new FrCadFeedback(new javax.swing.JFrame(), true, (Cliente) usuarioLogado);

        // Adiciona um listener para atualizar a tabela quando a tela de cadastro fechar
        telaCadastro.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                atualizarTabela(); // Recarrega os dados do banco
            }
        });

        telaCadastro.setVisible(true);
    }//GEN-LAST:event_btnDarFeedbackActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frFeedbackF().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDarFeedback;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTable gridComentarios;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
