/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Model.User;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class FrHome extends javax.swing.JFrame {

    private User ActiveUser;
    
    /**
     * Creates new form FrHome
     */
    public FrHome() {
        initComponents();
    }
    
    public void loginUser(User user){
        this.ActiveUser = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnClose.setText("Sair");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClose)
                    .addComponent(btnLogin))
                .addContainerGap(300, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnLogin)
                .addGap(18, 18, 18)
                .addComponent(btnClose)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // Abre a página de login.
        FrLogin loginPage = new FrLogin(this);
        
        loginPage.setLocationRelativeTo(this);
        loginPage.setVisible(true);
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
       System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    public void openMainPanel() {
    switch (this.ActiveUser.getNivelAcesso()) {
        case 1: // Gerente
            // Passamos o ActiveUser para o construtor que agora exige um User
            FrGerente frGerente = new FrGerente(this.ActiveUser); 
            frGerente.setVisible(true);
            this.dispose(); // Fecha a Home ao abrir o painel
            break;
            
        case 2: // Técnico
            // Passamos o ActiveUser para o construtor que agora exige um User
            FrTécnico frTecnico = new FrTécnico(this.ActiveUser); 
            frTecnico.setVisible(true);
            this.dispose();
            break;
            
        case 3: // Cliente
            // Certifique-se que FrCliente também receba o usuário no construtor
            FrCliente frCliente = new FrCliente(this.ActiveUser);
            frCliente.setVisible(true);
            this.dispose();
            break;
            
        default:
            JOptionPane.showMessageDialog(this, "Nível de acesso desconhecido!");
            break;
    }
}
    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLogin;
    // End of variables declaration//GEN-END:variables
}
