/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Model.User;
import Model.exceptions.ValidationException;
import controller.LoginController;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class FrLogin extends javax.swing.JFrame {

    LoginController controller = new LoginController();
    
    private FrHome parent;
    /**
     * Creates new form FrLoginF
     */
    public FrLogin() {
        initComponents();
    }
    
    public FrLogin(FrHome parent){
        initComponents();
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        edtUser = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MessageBar = new javax.swing.JTextArea();
        edtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setBackground(new java.awt.Color(102, 102, 102));
        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setText("PCMasterRace - Login");

        lblUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUser.setText("Usuário:");

        edtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtUserActionPerformed(evt);
            }
        });

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPassword.setText("Senha:");

        btnLogin.setText("Entrar");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        MessageBar.setColumns(20);
        MessageBar.setRows(5);
        jScrollPane1.setViewportView(MessageBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(edtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblPassword)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 20, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(edtPassword)))))
                        .addGap(0, 59, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnLogin)
                .addGap(160, 160, 160))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUser)
                    .addComponent(edtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(edtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtUserActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        // 1. Pegar os dados direto dos campos da tela
        String loginDigitado = edtUser.getText();

        // DICA DE SEGURANÇA: Para JPasswordField, use getPassword() e converta para String
        String senhaDigitada = new String(edtPassword.getText());

        try {
            // 2. Chama o controller. O método autenticar agora retorna um objeto Usuario (ou null)
            // E pode lançar (throw) uma ValidationException se os campos estiverem vazios.
            User usuarioLogado = (User) controller.autenticar(loginDigitado, senhaDigitada);

            if (usuarioLogado != null) {
                // --- CENÁRIO DE SUCESSO (Encontrou no Banco) ---

                // Se você usa aquele método do pai para gerenciar a sessão:
                this.parent.loginUser(usuarioLogado);
                this.parent.openMainPanel();
                // OU, se for abrir as janelas diretamente aqui:
                //direcionarUsuario(usuarioLogado);

                // Fecha a tela de login
                this.dispose();

            } else {
                // --- CENÁRIO DE FALHA (Banco não achou ninguém com esse login/senha) ---
                JOptionPane.showMessageDialog(this,
                        "Usuário ou senha incorretos!",
                        "Acesso Negado",
                        JOptionPane.ERROR_MESSAGE);
            }

        } catch (ValidationException e) {
            // --- CENÁRIO DE ERRO DE DIGITAÇÃO (ValidarLogin lançou erro) ---
            // A mensagem (e.getMessage()) será "Senha não pode ser nula", "Login muito curto", etc.
            JOptionPane.showMessageDialog(this,
                    e.getMessage(),
                    "Atenção",
                    JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea MessageBar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPasswordField edtPassword;
    private javax.swing.JTextField edtUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables

<<<<<<< HEAD
    
=======
    private void direcionarUsuario(User usuarioLogado) {
        switch (usuarioLogado.getNivelAcesso()) {
            case 1: // Gerente
                FrGerente frGerente = new FrGerente(); // Idealmente passe o user aqui também
                frGerente.setVisible(true);
                break;
            case 2: // Técnico
                FrTécnico frTecnico = new FrTécnico(); // Idealmente passe o user aqui também
                frTecnico.setVisible(true);
                break;
            case 3: // Cliente
                // AQUI ESTÁ A MÁGICA: Passamos o objeto logado para a tela
                FrCliente frCliente = new FrCliente(usuarioLogado);
                frCliente.setVisible(true);
                break;
            default:
                JOptionPane.showMessageDialog(this, "Nível de acesso desconhecido!");
                break;
        }
        this.dispose();
    }
    


}
>>>>>>> 77d91c18d0ae19ab4c00b601b51c1f3fb5238355
    
   
