/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.EstoqueDAO;
import jakarta.persistence.EntityManager;
import java.util.List;

/**
 *
 * @author gabri
 */
public class FrUpdateEstoque extends javax.swing.JDialog {

    /**
     * Creates new form FrUpdateEstoque
     */
    public FrUpdateEstoque(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.popularCombos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblCode = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        SelBoxAmount = new javax.swing.JComboBox<>();
        btnFinish = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        SelBoxType = new javax.swing.JComboBox<>();
        edtCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setText("Adicionar Produtos");

        lblCode.setText("Código:");

        lblAmount.setText("Quantidade");

        SelBoxAmount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SelBoxAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelBoxAmountActionPerformed(evt);
            }
        });

        btnFinish.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnFinish.setText("Finalizar");
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });

        btnAdd.setText("Adicionar");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        SelBoxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SelBoxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelBoxTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SelBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnFinish))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAmount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SelBoxAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtCode)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SelBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCode)
                    .addComponent(edtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmount)
                    .addComponent(SelBoxAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(btnFinish)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelBoxAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelBoxAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelBoxAmountActionPerformed

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFinishActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String codigoBusca = edtCode.getText().trim();
    String tipoSelecionado = (String) SelBoxType.getSelectedItem();
    int quantidadeParaAdicionar = Integer.parseInt((String) SelBoxAmount.getSelectedItem());

    if (codigoBusca.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Informe um código!");
        return;
    }

    EstoqueDAO dao = new EstoqueDAO();
    
    // O EntityManager será necessário para o merge (update)
    EntityManager em = dao.getEntityManager(); // Certifique-se que seu DAO expõe o EntityManager ou crie um aqui
    
    try {
        em.getTransaction().begin();

        if (tipoSelecionado.equals("Peça")) {
            List<Model.Pecas> lista = dao.listarPecas();
            Model.Pecas pecaEncontrada = null;

            for (Model.Pecas p : lista) {
                if (p.getCodigo().equals(codigoBusca)) {
                    pecaEncontrada = p;
                    break;
                }
            }

            if (pecaEncontrada != null) {
                // Soma a quantidade: Valor novo + Valor atual
                int novaQuantidade = pecaEncontrada.getQuant() + quantidadeParaAdicionar;
                pecaEncontrada.setQuant(novaQuantidade);
                em.merge(pecaEncontrada); // Atualiza no banco
                javax.swing.JOptionPane.showMessageDialog(this, "Peça atualizada! Nova quantidade: " + novaQuantidade);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Código de Peça não encontrado.");
            }

        } else if (tipoSelecionado.equals("Dispositivos")) {
            List<Model.Dispositivos> lista = dao.listarDispositivos();
            Model.Dispositivos dispositivoEncontrado = null;

            for (Model.Dispositivos d : lista) {
                if (d.getCodigo().equals(codigoBusca)) {
                    dispositivoEncontrado = d;
                    break;
                }
            }

            if (dispositivoEncontrado != null) {
                int novaQuantidade = dispositivoEncontrado.getQuant() + quantidadeParaAdicionar;
                dispositivoEncontrado.setQuant(novaQuantidade);
                em.merge(dispositivoEncontrado); // Atualiza no banco
                javax.swing.JOptionPane.showMessageDialog(this, "Dispositivo atualizado! Nova quantidade: " + novaQuantidade);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Código de Dispositivo não encontrado.");
            }
        }

        em.getTransaction().commit();
    } catch (Exception e) {
        if (em.getTransaction().isActive()) em.getTransaction().rollback();
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao processar: " + e.getMessage());
    } finally {
        em.close();
    }
    }//GEN-LAST:event_btnAddActionPerformed

    private void SelBoxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelBoxTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelBoxTypeActionPerformed

    private void popularCombos() {
        
        EstoqueDAO dao = new EstoqueDAO();
        //Popular Tipo
        SelBoxType.removeAllItems();
        SelBoxType.addItem("Peça");
        SelBoxType.addItem("Dispositivos");
        //Popular Quantidade
        // 1. Limpa todos os itens existentes
        SelBoxAmount.removeAllItems();
        // 2. Itera de 1 até 100
        for (int i = 1; i <= 100; i++) {
            // 3. Adiciona o número (convertido implicitamente para String) à JComboBox
            SelBoxAmount.addItem(String.valueOf(i)); 
        }
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SelBoxAmount;
    private javax.swing.JComboBox<String> SelBoxType;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnFinish;
    private javax.swing.JTextField edtCode;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

    void setVisible() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
